### PR TITLE
change isupper/islower to behave more like the python equivalent 

### PR DESCRIPTION
**Pull request by Kolpa**
isupper and islower are currently behaving in a way that is not consistent with the standard python implementation.

Normally calling isupper on a string like "AF_INET" will return true, but the current implementation will return false.

This fix will ignore all characters that have no upper or lowercase alternative, bringing the implementation closer to the python variant.

### CODE REVIEW

**Comment by timfel** [comment]
Thanks! Could please also add a test for this in `graalpython/com.oracle.graal.python.test/src/tests/test_string.py`

**Comment by milanpro** [comment]
Added test cases

**Comment by timfel** [comment]
Hi, sorry for the delay in merging this. This seems to have a side-effect on the unittests, we're running the `test_addinfo` test from `test_urllib_response`, and this change introduces a failure there. I'm investigating to see what's going on.

**Comment by Kolpa** [comment]
ocas should be signed now

**Comment by timfel** [comment]
Merged with https://github.com/graalvm/graalpython/commit/cad245f6466c1ecc892b2341d6a660943bedbe28

**Pull request closed without merging**
