### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Destaq**
Typo in README.md corrected:
I you're thinking -> If you're thinking.

### CODE REVIEW

**Comment by Destaq** [comment]
I'm unable to sign up, I received no email at my primary email address.

I guess we just have to hope someone notices this PR...

**Comment by msimacek** [comment]
Hi @Destaq, could you please forward me the email that you have sent?

**Comment by Destaq** [comment]
OK @msimacek, this is the email I received:
```
Hello --------, thanks for contributing a PR to our project!

We use the Oracle Contributor Agreement to make the copyright of contributions clear. We don't have a record of you having signed this yet, based on your email address 61620873+Destaq -(at)- users -(dot)- noreply -(dot)- github -(dot)- com. You can sign it at that link.

If you think you've already signed it, please comment below and we'll check.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
```

More specifically, I am unable to access the GitHub email: 61620873+Destaq -(at)- users -(dot)- noreply -(dot)- github -(dot)- com, and thus can't sign the agreeement.

**Comment by msimacek** [comment]
Ah, the bot doesn't see your github email address, because you don't have it publicly available on your profile. Would you consider making it visible? I can see your email address from your webpage that you link from your profile, so people can already find it easily, but not bots.

**Comment by Destaq** [comment]
That must have been it. I've made it public now.

**Comment by msimacek** [comment]
Thank you. Could you please now follow the procedure on [the OCA page](http://www.oracle.com/technetwork/community/oca-486395.html) using the email that you have set?

**Comment by Destaq** [comment]
Hmmm. I'm not comfortable with disclosing all of that just to fix a one character typo. I'm sure that you will correct it anyway if this PR is not merged.

**Pull request closed without merging**
